---
title: "Whose miles are these anyways? Estimating Site-Generated Vehicle Miles Traveled"
description: "*Journal of the American Planning Association*"
image: https://images.unsplash.com/photo-1506521781263-d8422e82f27a?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
author: 
  - Carole Turley Voulgaris
  - Greg Macfarlane
  - Joe Kaylor
date: "2024-01-22"
categories:
  - emerging data
  - activity-based models
  - environmental assessment
---

::: {.callout-note appearance="simple"}

## Citation

Turley Voulgaris, C., Macfarlane, G.S., Kaylor, J. (2024) Whose Miles Are These Anyway? Estimating Site-Generated Vehicle Miles Traveled, *Journal of the American Planning Association*, DOI: <https://doi.org/10.1080/01944363.2023.2298962>

:::

{{< downloadthis japa-sitevmt.pdf label="Download Author Copy" icon=file-earmark-pdf type=primary >}} 

## Problem, research strategy, and findings
State, local, and private-sector climate policies increasingly require estimates of site-generated vehicle miles traveled (VMT) for individual properties. No standard, agreed-upon method exists for this purpose. If alternative methods produce reasonably consistent results, then an analyst may select a method based on convenience. The purpose of this study was to determine whether this is the case. We reviewed existing applications and methods for estimating site-generated VMT, which can be conceptualized as the product of site-level trip generation and average length of a site-generated trip. We identified four plausible methods for estimating site-level trip generation and three for estimating average lengths of site-generated trips. Combining these yielded 12 methods for estimating site-generated VMT. We applied these methods to estimate trip generation, average trip length, and total VMT generated by eight existing office sites in the San Francisco Bay Area (CA) and the Wasatch Front Region of Utah. We found that trip generation and trip length estimates varied widely, with greater variation in trip generation estimates than in trip length estimates. Variation was magnified when the estimates were multiplied to produce site-generated VMT estimates, with the minimum estimate at a single site ranging from 84% to 96% lower than the corresponding maximum.

## Takeaway for practice

In the short term, planning policies requiring site developers or occupants to produce site-level estimates of VMT should specify consistent methods to allow for comparison across sites and over time as needed. In the long term, if VMT is to be used as a performance metric, industry-wide standards for estimating it for both existing and prospective projects are needed. Alternatively, policymakers should consider whether the goals of VMT reduction might be better met with a different performance metric.

Photo by <a href="https://unsplash.com/@john_matychuk?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">John Matychuk</a> on <a href="https://unsplash.com/photos/aerial-view-of-cars-parked-on-parking-lot-yvfp5YHWGsc?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
