project:
  type: website

execute:
  freeze: auto

website:
  title: "Greg Macfarlane"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://gregmacfarlane.github.io/lab
        text: Lab Manual
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



