project:
  type: website

execute:
  freeze: auto

website:
  title: "Greg Macfarlane"
  favicon: logo.png 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pubs.qmd
        text: Publications
      - href: https://gregmacfarlane.github.io/lab
        text: Lab Manual
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: 
      - yeti
      - custom.scss
    css: styles.css
    toc: true



