---
title: "The influences of past and present residential locations on vehicle ownership decisions."
description: "*Transportation Research Part A*"
image: https://images.unsplash.com/photo-1600727335606-1bb400010909?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1287&q=80
author: 
  - Greg Macfarlane
  - Laurie Garrow
  - Pat Mokhtarian
date: "2015-03-12"
categories:
  - travel behavior
  - emerging data
---

::: {.callout-note appearance="simple"}

## Citation

Macfarlane, G.S., Garrow, L.A., & Mokhtarian, P. L. (2015). The influences of past and present residential locations on vehicle ownership decisions. *Transportation Research Part A: Policy and Practice*, 74, 186–200. <https://doi.org/10.1016/j.tra.2015.01.005>
:::

{{< downloadthis learned_preferences.pdf dname=macfarlane_tra_autoown label="Download Preprint" icon=file-earmark-pdf type=primary >}}


This study explores the relationship between historical exposure to the built environment and current vehicle ownership patterns. The influence of past exposure to the built environment on current vehicle ownership decisions may be causal, but there are alternative explanations. Households may primarily select to live in neighborhoods that facilitate their vehicle ownership preferences, or they may retain preferences that they have developed in the past, irrespective of their current situations. This study seeks to control for these alternative explanations by including the built environment attributes of households’ past residences as an influence on vehicle ownership choices. We use a dataset from a credit reporting firm that contains up to nine previous residential ZIP codes for households currently living in the 13-county Atlanta, Georgia, metropolitan area. Results show that past location is significant, but of marginal influence relative to the attributes of the current location. From a practical perspective, our results suggest that models that include current but not past neighborhood attributes (also controlling for standard socioeconomic variables) can forecast vehicle ownership decisions reasonably well. However, models that include both current and past neighborhood attributes can provide a more nuanced understanding of the built environment’s potentially causal influences on vehicle ownership decisions. This better understanding may provide more realistic forecasts of responses to densification or other travel demand management strategies. 

> Photo by Jonas Jaeken on [Unsplash](https://unsplash.com/photos/1TmI9BTLmiU)