---
title: "Beyond proximity: utility-based access from location-based services data."
description: "*International Journal of Environmental Research and Public Health*"
image: https://images.unsplash.com/photo-1542838132-92c53300491e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80
author: 
  - Greg Macfarlane
  - Emma Stucki
  - Alisha Redelfs
  - Lori Spruance
date: "2022-09-28"
categories:
  - accessibility
  - emerging data
---
::: {.callout-note appearance="simple"}

## Citation
Macfarlane , G.S.; Stucki , E.; Redelfs , A.H.; Spruance , L.A. Beyond Proximity: Utility-Based Access from Location-Based Services Data. *Int. J. Environ. Res. Public Health* 2022, 19, 12352. <https://doi.org/10.3390/ijerph191912352>
:::

Understanding who in a community has access to its resources—parks, libraries, grocery stores, etc.—has profound equity implications, but typical methods to understand access to these resources are limited. Travel time buffers require researchers to assert mode of access as well as an arbitrary distance threshold; further, these methods do not distinguish between destination quality attributes in an effective way. In this research, we present a methodology to develop utility-based accessibility measures for parks, libraries, and grocery stores in Utah County, Utah. The method relies on passive location-based services data to model destination choice to these community resources; the destination choice model utility functions in turn allow us to develop a picture of regional access that is sensitive to: the quality and size of the destination resource; continuous (non-binary) travel impedance by multiple modes; and the sociodemographic attributes of the traveler. We then use this measure to explore equity in access to the specified community resources across income level in Utah County: the results reveal a discrepancy between which neighborhoods might be targeted for intervention using space-based analysis.

> Photo by nrd on [Unsplash](https://unsplash.com/photos/D6Tu_L3chLE)