---
title: "Identifying ridehail riders through pairing ActivitySim and BEAM"
description: "*The 17th International Conference on Ambient Systems, Networks and Technologies Networks*"
image: "https://images.unsplash.com/photo-1614091199036-e934784dbf0f?q=80&w=1976&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
author: 
  - Greg Macfarlane
date: "2026-07-01"
categories:
  - traffic performance
  - emerging data
---

::: {.callout-note appearance="simple"}

## Citation

Macfarlane, G. S., Day, C., Erhardt, G. D., & Watkins, K. E. (2026). Identifying ridehail riders through pairing ActivitySim and BEAM. *Procedia Computer Science*, The 17th International Conference on Ambient Systems, Networks and Technologies Networks (ANT)/ the 9th International Conference on Emerging Data and Industry 4.0 (EDI40), 280, 286–293. https://doi.org/10.1016/j.procs.2026.04.038

:::

{{< downloadthis abmtrans-modechoice.pdf dname=macfarlane-modechoice.pdf label="Download Preprint" icon=file-earmark-pdf type=primary >}}

The advent of on-demand transport modes such as ride-hailing and microtransit has challenged forecasters to develop new methods of forecasting the use and impacts of such modes. In particular, there is some professional disagreement about the relative role of activity-based transportation behavior models — which have detailed understanding of the person making a trip and its purpose — and multi-agent demand simulations which may have a better understanding of the availability and service characteristics of on-demand services. A particular question surrounds how the relative strengths of these two approaches might be successfully paired in practice. Using daily plans generated by the activity-based model ActivitySim as inputs to the BEAM multi-agent simulation, we construct nine different methodological combinations by allowing the choice to use a pooled ride-hail service in ActivitySim, in BEAM with different utility functions, or in both. Within each combination, we estimate ride-hailing ridership and level of service measures. The results suggest that mode choice model structure drastically affects ride-hailing ridership and level of service. In addition, we see that multi-agent simulation overstates the demand interest relative to an activity-based model, but there may be opportunities in future research to implement feedback loops to balance the ridership and level of service forecasts between the two models.

> Photo by <a href="https://unsplash.com/@thibaultpenin?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Thibault Penin</a> on <a href="https://unsplash.com/photos/man-in-black-jacket-driving-car-during-daytime-a8r2KKLSntA?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>